### ISSUE TITLE
Bad Call to the API

### ISSUE THREAD

**Issue by kraxarn** [Sorashi/Cleverbot.Net#1]
When trying to send a message after creating a session, I get the following error
```
System.AggregateException: 'One or more errors occurred.'

Inner Exception
Exception: Error: Bad Call to the API
```

EDIT: After some more testing, this seems to be more of an issue with Cleverbot.IO itself and not with this library

**Comment by Beysinvader** [comment]
did you fixed it ?
if yes, how?

**Comment by kraxarn** [comment]
Cleverbot.IO was having some downtime. Now the library works just fine.
