### ISSUE TITLE
Can Language Change?

### ISSUE THREAD

**Issue by Artzalez** [Sorashi/Cleverbot.Net#2]

**Comment by sorashi** [comment]
@DevBiiTz unfortunately no, not at the moment. This is a wrapper around [cleverbot.io](https://docs.cleverbot.io/docs/).

There is however another cleverbot provider – Cleverbot.com responds to your messages in the language you post them. If that's enough for you, go for [this library](https://github.com/velddev/cleverbot.net), which implements Cleverbot.com. However, Cleverbot.com API is paid (there is 5000 API calls free trial though).

In this repo, there is a branch in which I'm implementing Cleverbot.com and generalizing the OOP, so we can use any cleverbot provider.
