### ISSUE TITLE
Is Cleverbot.io dead? 

### ISSUE THREAD

**Issue by Straafe** [Sorashi/Cleverbot.Net#4]
I know it was going down a while ago sporadically and I heard talk it was no longer being supported. Now the website is working awkwardly (but the website's chatbot still works) and this .Net wrapper is no longer working.  Getting a:

System.Net.Webexception: The remote server returned an error: (524) Origin Time-out

On the line:

session = await CleverbotSession.NewSessionAsync("xxxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxx");

The code has been working for months now so I'm thinking the entire cleverbot.io might be dead

**Comment by beminee** [comment]
@Straafe It's working fine for me, maybe getting a new key would solve your problem.

**Comment by Straafe** [comment]
Bizarre. It works fine again now. I tried it once an hour for 48 hours around the time I posted and it never worked, but now it does again!
