### ISSUE TITLE
Cleverbot.io API down

### ISSUE THREAD

**Issue by Sidewardduke** [Sorashi/Cleverbot.Net#5]
None of the calls I make to the API work, I always get a time out response back from it. On the site, it says that 0 API calls have been made and the discussion part of the site that used to be up was just filled with people saying that it's down or broken with no answer.

**Comment by owocean** [comment]
Someone please answer this im having the same issue

**Comment by sorashi** [comment]
Looks like the cleverbot.io API is really down. If you need a more stable option I recommend cleverbot.com. There is a [.NET wrapper](https://github.com/velddev/Cleverbot.Net) for it. The API is paid though, it's $10 for 10k requests per month, see [pricing](https://www.cleverbot.com/api/#abovetitle).

There is also a free alternative – a [web scrapper](https://github.com/plasticuproject/cleverbotfree) for cleverbot.com, which actually uses a browser to visit cleverbot.com and send and receive messages. It's written in Python so using it from .NET wouldn't be easy, but it's possible imo. Another option is to implement the same thing in .NET, but that would take a long time. I might look into doing it soon, no promises though.

**Comment by bddvlpr** [comment]
Is it ever gonna get fixed or have they abandoned the project?

**Comment by sorashi** [comment]
@StijnSimons I tried contacting someone who seems to be a maintainer and has been active on GitHub this month, subscribe to https://github.com/elifoster/gp-work-utils/issues/4 for updates.

**Comment by sorashi** [comment]
I sent an email to @dtesler who is apparently the maintainer of the project. He hasn't been active for 2 years, though. I will post an update here if he responds.

**Comment by sorashi** [comment]
> I sent an email to @dtesler who is apparently the maintainer of the project. He hasn't been active for 2 years, though. I will post an update here if he responds.

He hasn't responded for 6 days, so I assume he is either on a vacation or has left the internet (or merely abandoned his email).

**Comment by Yota002** [comment]
> 
> 
> Looks like the cleverbot.io API is really down. If you need a more stable option I recommend cleverbot.com. There is a [.NET wrapper](https://github.com/velddev/Cleverbot.Net) for it. The API is paid though, it's $10 for 10k requests per month, see [pricing](https://www.cleverbot.com/api/#abovetitle).
> 
> There is also a free alternative – a [web scrapper](https://github.com/plasticuproject/cleverbotfree) for cleverbot.com, which actually uses a browser to visit cleverbot.com and send and receive messages. It's written in Python so using it from .NET wouldn't be easy, but it's possible imo. Another option is to implement the same thing in .NET, but that would take a long time. I might look into doing it soon, no promises though.

I apologize, but do you know any cleverbot.com web scrapper alternatives for node.js?

**Comment by sorashi** [comment]
@Yota002 I don't, but a quick search reveals that [there have been attempts](https://github.com/Yernemm/Cleverbot-Nodejs-Scraper), maybe you can work from there

**Comment by Macleykun** [comment]
Any update on this? I try to find some good alternative but there is none i can find.
Using a web scrabber uses alot of resources, as i try to find smth that can be incoparted into a plugin system of a bot.

**Comment by sorashi** [comment]
@Macley-Kun nothing new has happened, sorry. If you're looking for a low-resource solution, I don't know about anything that's for free. You could always pay for the cleverbot.com API though.

**Comment by Macleykun** [comment]
It's ok, i ofcours hope that oneday the API comes back up, meanwhile i found these two:
https://botlibre.com/api.jsp
https://botmakr.net/help/api/

Not wanna advertise, but it seems like a semi-solution to this issue what's been going on.

**Comment by Macleykun** [comment]
I think this project isn’t maintained anymore.
Perhaps it’s time to archive/put it on read-only?
And close this issue?
