### ISSUE TITLE
Can't login to Cleverbot.io

### ISSUE THREAD

**Issue by jn-sena** [Sorashi/Cleverbot.Net#6]
I needed to get a key, so I went to [Cleverbot's login site](https://cleverbot.io/login) and clicked on login, I logged in to [Skillflow.io](https://skillflow.io/), but when i try to login Cleverbot, it times out. I even tried with different OAuths or creating an account.

**Comment by sorashi** [comment]
Cleverbot.io is not maintained by its authors anymore, see #5
